apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jeeb-obs-ingress
  namespace: {{ .Values.namespace }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: grafana.jeeb.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  number: 3000
