apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: {{ .Values.global.namespace }}
spec:
  type: {{ .Values.global.serviceType }}
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
      {{- if eq .Values.global.serviceType "NodePort" }}
      nodePort: {{ .Values.mongodb.nodePort }}
      {{- end }}
