apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus
  namespace: jeeb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
    spec:
      containers:
        - name: nexus
          image: sonatype/nexus3:latest
          ports:
            - containerPort: 8081
            - containerPort: 5000
          env:
            - name: INSTALL4J_ADD_VM_PARAMS
              value: "-Xms512m -Xmx1024m -XX:MaxDirectMemorySize=512m"
          volumeMounts:
            - name: nexus-data
              mountPath: /nexus-data
          resources:
            requests:
              memory: 1Gi
              cpu: 250m
            limits:
              memory: 2Gi
              cpu: 1000m
          readinessProbe:
            httpGet:
              path: /service/rest/v1/status
              port: 8081
            initialDelaySeconds: 90
            periodSeconds: 15
      volumes:
        - name: nexus-data
          persistentVolumeClaim:
            claimName: nexus-pvc
