global:
  env: develop
  namespace: jeeb-dev
  domain: jeeb-dev.local
  imageTag: latest

ingress:
  cors:
    enabled: true
    allowOrigin: https://learning.jeeb-dev.local

backend:
  vault:
    path: secret/data/jeeb/learning/backend/develop
    envFile: .env.develop

frontend:
  vault:
    path: secret/data/jeeb/learning/frontend/develop
    envFile: .env.develop
