apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-agent-config
  namespace: jeeb
data:
  agent.hcl: |
    vault {
      address = "http://vault.jeeb.svc.cluster.local:8200"
    }

    auto_auth {
      method "kubernetes" {
        mount_path = "auth/kubernetes"
        config = {
          role = "backend"
        }
      }

      sink "file" {
        config = {
          path = "/app/env/.vault-token"
        }
      }
    }

    template {
      source      = "/vault/config/env-develop.tpl"
      destination = "/app/env/.env.develop"
      perms       = "0640"
    }

  env-develop.tpl: |
    {{- with secret "secret/data/jeeb/backend/develop" -}}
    GO_ENV=develop
    PORT={{ .Data.data.PORT }}
    LOG_LEVEL={{ .Data.data.LOG_LEVEL }}
    READ_TIMEOUT={{ .Data.data.READ_TIMEOUT }}
    WRITE_TIMEOUT={{ .Data.data.WRITE_TIMEOUT }}
    MONGO_DATABASE={{ .Data.data.MONGO_DATABASE }}
    MONGO_URI={{ .Data.data.MONGO_URI }}
    KEYCLOAK_URL={{ .Data.data.KEYCLOAK_URL }}
    KEYCLOAK_REALM={{ .Data.data.KEYCLOAK_REALM }}
    KEYCLOAK_CLIENT_ID={{ .Data.data.KEYCLOAK_CLIENT_ID }}
    {{- end }}
