apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: {{ .Values.namespace }}
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        uid: prometheus
        type: prometheus
        url: http://prometheus.{{ .Values.namespace }}.svc.cluster.local:9090
        isDefault: true
        jsonData:
          timeInterval: 15s

      - name: Loki
        uid: loki
        type: loki
        url: http://loki.{{ .Values.namespace }}.svc.cluster.local:3100
        jsonData:
          derivedFields:
            - datasourceUid: tempo
              matcherRegex: '"trace_id":"([a-f0-9]+)"'
              name: TraceID
              url: "$${__value.raw}"
              urlDisplayLabel: View Trace

      - name: Tempo
        uid: tempo
        type: tempo
        url: http://tempo.{{ .Values.namespace }}.svc.cluster.local:3200
        jsonData:
          tracesToLogsV2:
            datasourceUid: loki
            tags:
              - key: app
          serviceMap:
            datasourceUid: prometheus
          nodeGraph:
            enabled: true
          lokiSearch:
            datasourceUid: loki
