namespace: jeeb-infra

kong:
  image: kong:3.9
  nodePort: 30088
  appNamespace: jeeb-dev
  # Token iss claim — must match exactly what Keycloak puts in the JWT.
  keycloakIssuer: "http://auth.jeeb-dev.local/realms/jeeb"
  # RS256 public key in PEM format.
  keycloakPublicKey: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwti1NWxawKdVWz8JhjeE
    I5yKznXNIqJwE/Pb3HbBNmLwkXuiR8egv3hUWkWs3Qkno4Kh3rpuplzvqg0R7lvo
    q0jjGL56vjgOINZqJvG1AfbN+pRCT/QwZ4o/QxSY94l6kVv3a7D8doKTax3eGVfL
    2WoWkUlxj9atIanIIqNAM2hVvYKo2xivyT7e7oxocA+exQBrQXaHeE1TSUlG5ljQ
    aKsC/tGGhPSsmdUnKOUIUYpp0bsAEM7X4VVPJ0PngEum/wxY/rcbeB/y5eJQHMRv
    IDB99ZvJ02tvYcKWJ5IXNSVp2ilDwAvDsOgwfGeIBgJP/RjcWwfNseRI2KJW8VR/
    dQIDAQAB
    -----END PUBLIC KEY-----

vault:
  image: hashicorp/vault:1.17
  storageSize: 2Gi
  nodePort: 30091
  clusterName: jeeb-infra

jenkins:
  image: jenkins/jenkins:lts-jdk17
  storageSize: 5Gi
  nodePort: 30082
  agentNodePort: 30500
  jenkinsRepo: "https://github.com/kittitadkp/jeeb-jenkins.git"
  credentials:
    adminPassword: "K@ng_12092540"
    githubUser: "kittitadkp"
    githubPat: "PLACEHOLDER_GITHUB_PAT"
    nexusUser: "admin"
    nexusPat: "admin123"
    sonarToken: "squ_4cfe749941a6aea97dd29a3679dbd11caeae139b"
  plugins:
    - git
    - git-client
    - workflow-aggregator
    - pipeline-model-definition
    - workflow-scm-step
    - workflow-cps
    - workflow-job
    - job-dsl
    - configuration-as-code
    - kubernetes
    - pipeline-stage-view
    - timestamper
    - ansicolor
    - build-timeout
    - ws-cleanup
    - sonar
    - github
    - github-branch-source

nexus:
  image: sonatype/nexus3:latest
  storageSize: 10Gi
  uiNodePort: 30083
  registryNodePort: 30050

sonarqube:
  image: sonarqube:10-community
  storageSize: 5Gi
  nodePort: 30090

ingress:
  className: nginx
  hosts:
    vault: vault.jeeb.local
    jenkins: jenkins.jeeb.local
    nexus: nexus.jeeb.local
    sonarqube: sonarqube.jeeb.local
