apiVersion: v1
kind: Secret
metadata:
  name: jenkins-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  admin-password: {{ .Values.jenkins.credentials.adminPassword | quote }}
  github-user: {{ .Values.jenkins.credentials.githubUser | quote }}
  github-pat: {{ .Values.jenkins.credentials.githubPat | quote }}
  nexus-user: {{ .Values.jenkins.credentials.nexusUser | quote }}
  nexus-pat: {{ .Values.jenkins.credentials.nexusPat | quote }}
  sonar-token: {{ .Values.jenkins.credentials.sonarToken | quote }}
