apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jeeb-data-ingress
  namespace: {{ .Values.global.namespace }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: auth.{{ .Values.ingress.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 8080
