global:
  env: develop
  namespace: jeeb-dev
  domain: jeeb-dev.local
  imageTag: latest

keycloak:
  hostnameUrl: https://auth.jeeb-dev.local

ingress:
  cors:
    enabled: true
    allowOrigin: https://jeeb-dev.local

backend:
  vault:
    path: secret/data/jeeb/backend/develop
    envFile: .env.develop

frontend:
  pullPolicy: Always
  vault:
    path: secret/data/jeeb/frontend/develop
    envFile: .env.develop
