apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  namespace: {{ .Values.namespace }}
data:
  vault.hcl: |
    ui            = true
    cluster_name  = "{{ .Values.vault.clusterName }}"

    listener "tcp" {
      address     = "0.0.0.0:8200"
      tls_disable = true
    }

    storage "file" {
      path = "/vault/data"
    }

    api_addr     = "http://vault.{{ .Values.namespace }}.svc.cluster.local:8200"
    cluster_addr = "http://vault.{{ .Values.namespace }}.svc.cluster.local:8201"
