apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: jeeb
type: Opaque
stringData:
  username: jeeb
  password: jeeb123
  uri: mongodb://jeeb:jeeb123@mongodb.jeeb.svc.cluster.local:27017/jeeb?authSource=admin
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  namespace: jeeb
type: Opaque
stringData:
  admin-user: admin
  admin-password: admin123
