apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: {{ .Values.global.namespace }}
spec:
  type: {{ .Values.global.serviceType }}
  selector:
    app: keycloak
  ports:
    - port: 8080
      targetPort: 8080
      {{- if eq .Values.global.serviceType "NodePort" }}
      nodePort: {{ .Values.keycloak.nodePort }}
      {{- end }}
