certManager:
  version: v1.15.3
  namespace: cert-manager

rancher:
  version: 2.9.3
  namespace: cattle-system
  hostname: rancher.jeeb-infra.local
  tlsSource: rancher      # self-signed via cert-manager
  replicas: 1
  nodePort: 30443

ingress:
  className: nginx
