apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jeeb-learning-ingress
  namespace: {{ .Values.global.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: learning.{{ .Values.ingress.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: learning-frontend
                port:
                  number: 80

    - host: learning-api.{{ .Values.ingress.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: learning-backend
                port:
                  number: 8080
