apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault
  namespace: jeeb
---
# Allows Vault's Kubernetes auth method to validate pod service account tokens
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault-auth-delegator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: vault
    namespace: jeeb
