apiVersion: v1
kind: Service
metadata:
  name: nexus
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: nexus
  ports:
    - name: ui
      port: 8081
      targetPort: 8081
      nodePort: {{ .Values.nexus.uiNodePort }}
    - name: registry
      port: 5000
      targetPort: 5000
      nodePort: {{ .Values.nexus.registryNodePort }}
